### ISSUE TITLE
Nova forma de propor desafios

### ISSUE THREAD

**Issue by RuanGOA** [MariaEduardaDeAzevedo/nosso-py#9]
Acredito que um iniciante na linguagem ficaria mais engajado diante de problemas de diversos níveis de conhecimento, então, o que proponho é algum lugar no repositório para colocar problemas(ou listas de problemas) e soluções para esses.

Há sites de julgamento online de soluções para problemas propostos, como o [**CodeForces**](https://codeforces.com/) e o [**URI**](https://www.urionlinejudge.com.br/judge/pt).

**Comment by RuanGOA** [comment]
Além do mais, com isso, abriria mais o leque de possibilidades para criar um PR no repositório. E acho que seria necessário encontrar alguma maneira de padronizar para que não houvessem duas soluções para o mesmo problema do mesmo site, como 
_uri-1000.cpp_, ou algo do tipo.

**Comment by MariaEduardaDeAzevedo** [comment]
Gostei muito das ideias, vou fazer umas alterações e adições com base nisso, valeu!

**Comment by MariaEduardaDeAzevedo** [comment]
Fiz umas alterações baseadas nas tuas ideias! 

1. Adicionei agora um diretório só para resoluções, que podem receber contribuições tanto de respostas como de sujestões para a galera resolver questões de outras plataformas.
2. Dei uma alterada no modo de enviar desafios direto direto para cá, o mesmo para os mini-projetos, acredito que ficou mais cômodo e organizado que antes.

Vou fechar essa issue para abrir espaço de mais ideias em cima das novas alterações, pode ficar à vontade para dar mais ideias! Mais uma vez, muito obrigada @RuanGOA !
